services:
  stats-db:
    image: postgres:16.1

  event-db:
    image: postgres:16.1
    container_name: event-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=event

  user-db:
    image: postgres:16.1
    container_name: user-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user

  request-db:
    image: postgres:16.1
    container_name: request-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=request

  compilation-db:
    image: postgres:16.1
    container_name: compilation-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=compilation

  ewm-db:
    image: postgres:16.1
