import "stats/messages/analyzer/analyzer_messages.proto";

option java_package = "ru.practicum.ewm.stats.proto";

package stats.service.dashboard;

service RecommendationsController {
  rpc GetRecommendationsForUser(stats.message.UserPredictionsRequestProto)
      returns (stream stats.message.RecommendedEventProto);

  rpc GetSimilarEvents(stats.message.SimilarEventsRequestProto)
      returns (stream stats.message.RecommendedEventProto);

  rpc GetInteractionsCount(stats.message.InteractionsCountRequestProto)
      returns (stream stats.message.RecommendedEventProto);
}