spring:
  application:
    name: compilation-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
      retry:
        use-random-policy: true
        max-interval: 6000

  config:
    import: "configserver:"

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 0